[2022-07-22 14:10:01,600] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: load_data.create_dataset_table manual__2022-07-22T11:09:59.384365+00:00 [queued]>
[2022-07-22 14:10:01,602] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: load_data.create_dataset_table manual__2022-07-22T11:09:59.384365+00:00 [queued]>
[2022-07-22 14:10:01,602] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 14:10:01,602] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-07-22 14:10:01,602] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 14:10:01,612] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_dataset_table> on 2022-07-22 11:09:59.384365+00:00
[2022-07-22 14:10:01,614] {standard_task_runner.py:52} INFO - Started process 17844 to run task
[2022-07-22 14:10:01,615] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'load_data', 'create_dataset_table', 'manual__2022-07-22T11:09:59.384365+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_data_loader.py', '--cfg-path', '/tmp/tmpwxmxkdhl', '--error-file', '/tmp/tmpawl1do13']
[2022-07-22 14:10:01,616] {standard_task_runner.py:80} INFO - Job 19: Subtask create_dataset_table
[2022-07-22 14:10:01,627] {logging_mixin.py:115} WARNING - /home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2022-07-22 14:10:01,641] {task_command.py:371} INFO - Running <TaskInstance: load_data.create_dataset_table manual__2022-07-22T11:09:59.384365+00:00 [running]> on host hp-HP-Pavilion-Laptop-15-eg0xxx
[2022-07-22 14:10:01,670] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tesfaye
AIRFLOW_CTX_DAG_ID=load_data
AIRFLOW_CTX_TASK_ID=create_dataset_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-22T11:09:59.384365+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-22T11:09:59.384365+00:00
[2022-07-22 14:10:01,684] {base.py:68} INFO - Using connection ID 'postgres_connection' for task execution.
[2022-07-22 14:10:01,691] {sql.py:255} INFO - Running statement: CREATE TABLE IF NOT EXISTS raw_data
(
    id bigint,
    track_id bigint,
    " type" text COLLATE pg_catalog."default",
    " traveled_d" double precision,
    " avg_speed" double precision,
    " lat" double precision,
    " lon" double precision,
    " speed" double precision,
    " lon_acc" double precision,
    " lat_acc" double precision,
    "time" double precision,
    other_data text COLLATE pg_catalog."default"
), parameters: None
[2022-07-22 14:10:01,691] {postgres.py:94} INFO - NOTICE:  relation "raw_data" already exists, skipping

[2022-07-22 14:10:01,694] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=load_data, task_id=create_dataset_table, execution_date=20220722T110959, start_date=20220722T111001, end_date=20220722T111001
[2022-07-22 14:10:01,707] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 14:10:01,723] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
